### PR TITLE
[feature]add API for checking name and revision

### PR DESCRIPTION
**Pull request by yutako0217**
Hi Kazuu,

Let me add a feature which provides checking name and version of Cloud Run.
If it run on local, this API will response name=local, version=blank.

### CODE REVIEW

**Review by kazshinohara — COMMENTED** [review]
Thanks for PR, Cloud Run's revision does not mean "version" of this app, revision is automatically created per gcloud run deploy.  I would like the terminology consistency for what you call(request url path) and what you see(response body).  Why don't you return value of environment variable "VERSION" which you set when you deploy Cloud Run service instead of using "K_REVISION" ?

**Comment by yutako0217** [comment]
I think it would be useful if the API returns Cloud Run Info for a demo of Cloud Run part.
How about changing path to /runinfo instead of /version?

**Comment by kazshinohara** [comment]
Ok, understood that you like to get service name and revision name  during your hands-on.  Please take "/run/info" or "/run-info" these are more RESTful and readable.

**Comment by yutako0217** [comment]
Thanks, Kazuu.
I updated path url as `/run-info/` and method name as `read_run_info`.

**Pull request merged**
